mv bilinint.cpython-36m-darwin.so bilinint.so
mv chisq.cpython-36m-darwin.so chisq.so
mv deramp.cpython-36m-darwin.so deramp.so
mv ellke.cpython-36m-darwin.so ellke.so
mv ellpic_bulirsch.cpython-36m-darwin.so ellpic_bulirsch.so
mv expramp.cpython-36m-darwin.so expramp.so
mv fallingexp.cpython-36m-darwin.so fallingexp.so
mv felramp.cpython-36m-darwin.so felramp.so
mv linramp.cpython-36m-darwin.so linramp.so
mv llramp.cpython-36m-darwin.so llramp.so
mv log4qramp.cpython-36m-darwin.so log4qramp.so
mv logramp.cpython-36m-darwin.so logramp.so
mv lqramp.cpython-36m-darwin.so lqramp.so
mv mandelecl.cpython-36m-darwin.so mandelecl.so
mv mandeltr.cpython-36m-darwin.so mandeltr.so
mv nnint.cpython-36m-darwin.so nnint.so
mv occultquad.cpython-36m-darwin.so occultquad.so
mv quadip.cpython-36m-darwin.so quadip.so
mv quadramp.cpython-36m-darwin.so quadramp.so
mv re2ramp.cpython-36m-darwin.so re2ramp.so
mv relramp.cpython-36m-darwin.so relramp.so
mv reqramp.cpython-36m-darwin.so reqramp.so
mv risingexp.cpython-36m-darwin.so risingexp.so
mv rotation.cpython-36m-darwin.so rotation.so
mv rsky.cpython-36m-darwin.so rsky.so
mv se2ramp.cpython-36m-darwin.so se2ramp.so
mv selramp.cpython-36m-darwin.so selramp.so
mv seqramp.cpython-36m-darwin.so seqramp.so
mv seramp.cpython-36m-darwin.so seramp.so
mv sincos2.cpython-36m-darwin.so sincos2.so
mv trnlldsp.cpython-36m-darwin.so trnlldsp.so
mv vsll.cpython-36m-darwin.so vsll.so
