#!/bin/bash
mv bilinint.cpython-*.so bilinint.so
mv chisq.cpython-*.so chisq.so
mv deramp.cpython-*.so deramp.so
mv ellke.cpython-*.so ellke.so
mv ellpic_bulirsch.cpython-*.so ellpic_bulirsch.so
mv expramp.cpython-*.so expramp.so
mv fallingexp.cpython-*.so fallingexp.so
mv felramp.cpython-*.so felramp.so
mv linramp.cpython-*.so linramp.so
mv llramp.cpython-*.so llramp.so
mv log4qramp.cpython-*.so log4qramp.so
mv logramp.cpython-*.so logramp.so
mv lqramp.cpython-*.so lqramp.so
mv mandelecl.cpython-*.so mandelecl.so
mv mandeltr.cpython-*.so mandeltr.so
mv nnint.cpython-*.so nnint.so
mv occultquad.cpython-*.so occultquad.so
mv quadip.cpython-*.so quadip.so
mv quadramp.cpython-*.so quadramp.so
mv re2ramp.cpython-*.so re2ramp.so
mv relramp.cpython-*.so relramp.so
mv reqramp.cpython-*.so reqramp.so
mv risingexp.cpython-*.so risingexp.so
mv rotation.cpython-*.so rotation.so
mv rsky.cpython-*.so rsky.so
mv se2ramp.cpython-*.so se2ramp.so
mv selramp.cpython-*.so selramp.so
mv seqramp.cpython-*.so seqramp.so
mv seramp.cpython-*.so seramp.so
mv sincos2.cpython-*.so sincos2.so
mv trnlldsp.cpython-*.so trnlldsp.so
mv vsll.cpython-*.so vsll.so
